#
# Global Configuration
#

#development:
url:
  site: http://getupcloud.com/
  register: https://broker.getupcloud.com/getup/account/signup/

  broker: https://broker.getupcloud.com
  # broker: http://localhost:3000
